# Generated by Django 3.1.2 on 2020-12-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=255)),
                ('Адрес', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Телефон', models.CharField(max_length=255)),
                ('Изображение', models.ImageField(upload_to='images_invent/')),
                ('Информация', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
