# Generated by Django 3.1.2 on 2020-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Телефон',
        ),
        migrations.AlterField(
            model_name='image',
            name='Адрес',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Информация',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Название',
            field=models.TextField(),
        ),
    ]
