# Generated by Django 3.1.2 on 2020-12-07 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0010_auto_20201207_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Application',
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
