# Generated by Django 3.1.2 on 2020-12-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20201207_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Адрес',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Изображение',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Информация',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Название',
            new_name='title',
        ),
    ]
