# Generated by Django 3.1.2 on 2021-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20210129_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
