# Generated by Django 3.1.2 on 2021-03-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0015_step_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='address',
            new_name='applicants_address',
        ),
        migrations.AddField(
            model_name='application',
            name='agreement',
            field=models.FileField(default=1, upload_to='documents/patent/agreement/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='authors_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='essay',
            field=models.FileField(default=1, upload_to='documents/patent/essay/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='statement',
            field=models.FileField(default=1, upload_to='documents/patent/statement/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='documents/patent/image/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/polygraph/'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
