# Generated by Django 3.1.2 on 2021-03-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_auto_20210317_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/polygraph/')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='paid_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='paid_second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
